### ISSUE TITLE
Add msg used to publish encoder information

### ISSUE THREAD

**Issue by markwomack** [victoriarobotics/victoria_msgs#11]
@griswaldbrooks - Any preference to have the msg represent only a single encoder or both encoders in the same msg?

**Comment by griswaldbrooks** [comment]
I feel like a single encoder message is better. That way, if one wheel turns and the other doesn't (or anything like that), you're not sending the same info multiple times. That's the only difference I see off hand.

**Comment by markwomack** [comment]
#12
